/**
 * Object configuration for the Open Office 3D map.
 * meshName must exactly match the node name in the GLTF scene graph
 * as exported from Blender.
 */
export const OBJECTS = [
  {
    meshName: 'FireExtinguisher_1',
    name: 'Fire Extinguisher 1',
    category: 'Fire Safety',
    icon: '🧯',
    location: 'Zone A - East Wall',
    description: 'CO₂ fire extinguisher rated for Class B and C fires. Suitable for electrical and flammable liquid fires. Inspect monthly and service annually.',
    contact: 'Safety Officer',
    photo: null,
    camDir: [0.3, 0.4, -1],
  },
  {
    meshName: 'FireExtinguisher_2',
    name: 'Fire Extinguisher 2',
    category: 'Fire Safety',
    icon: '🧯',
    location: 'Zone B - North Corridor',
    description: 'CO₂ fire extinguisher rated for Class B and C fires. Suitable for electrical and flammable liquid fires. Inspect monthly and service annually.',
    contact: 'Safety Officer',
    photo: null,
  },
  {
    meshName: 'FireExtinguisher_3',
    name: 'Fire Extinguisher 3',
    category: 'Fire Safety',
    icon: '🧯',
    location: 'Zone C - West Wall',
    description: 'CO₂ fire extinguisher rated for Class B and C fires. Suitable for electrical and flammable liquid fires. Inspect monthly and service annually.',
    contact: 'Safety Officer',
    photo: null,
  },
  {
    meshName: 'FireExtinguisher_4',
    name: 'Fire Extinguisher 4',
    category: 'Fire Safety',
    icon: '🧯',
    location: 'Zone D - South Exit',
    description: 'CO₂ fire extinguisher rated for Class B and C fires. Suitable for electrical and flammable liquid fires. Inspect monthly and service annually.',
    contact: 'Safety Officer',
    photo: null,
    camDir: [1, 0.4, 0],
  },
  {
    meshName: 'FireExtinguisher_5',
    name: 'Fire Extinguisher 5',
    category: 'Fire Safety',
    icon: '🧯',
    location: 'Zone E - Server Room',
    description: 'CO₂ fire extinguisher rated for Class B and C fires. Suitable for electrical and flammable liquid fires. Inspect monthly and service annually.',
    contact: 'Safety Officer',
    photo: null,
    camDir: [-1, 0.4, -1],
  },
  {
    meshName: 'Exit_Sign_Box',
    name: 'Emergency Exit',
    category: 'Emergency Egress',
    icon: '🚪',
    location: 'Main Exit - North Wing',
    description: 'Illuminated emergency exit sign with battery backup. Indicates primary evacuation route. Exit leads to the assembly point in the parking area. Keep path clear at all times.',
    contact: 'Facility Manager',
    photo: null,
    camDir: [0, 0.3, -1],
  },
  {
    meshName: 'FireAlarmButton',
    name: 'Fire Alarm Button',
    category: 'Emergency Alert',
    icon: '🚨',
    location: 'Central Office - Corridor',
    description: 'Manual call point for the building fire alarm system. Break glass and press to trigger full building evacuation alarm. Do not use for testing without notifying building management.',
    contact: 'Emergency: 112',
    photo: null,
    camDir: [0, 0.3, -1],
  },
  {
    meshName: 'conf_table_1',
    name: 'Conference Table 1',
    category: 'Meeting Room',
    icon: '🪑',
    location: 'Meeting Room A',
    description: 'Main conference table seating up to 10 people. Equipped with power outlets, HDMI connections, and wireless screen sharing. Available for booking through the office calendar system.',
    contact: 'Reception',
    photo: null,
  },
  {
    meshName: 'conf_table_2',
    name: 'Conference Table 2',
    category: 'Meeting Room',
    icon: '🪑',
    location: 'Meeting Room B',
    description: 'Mid-size conference table seating up to 6 people. Equipped with power outlets and HDMI connections. Available for booking through the office calendar system.',
    contact: 'Reception',
    photo: null,
  },
  {
    meshName: 'conf_table_3',
    name: 'Conference Table 3',
    category: 'Meeting Room',
    icon: '🪑',
    location: 'Meeting Room C',
    description: 'Small conference table seating up to 4 people. Ideal for focused team discussions or client calls. Available for booking through the office calendar system.',
    contact: 'Reception',
    photo: null,
  },
  {
    meshName: 'FirstAidCabinetBody',
    name: 'First Aid Cabinet',
    category: 'First Aid',
    icon: '🩺',
    location: 'Central Office - North Wall',
    description: 'Wall-mounted first aid cabinet stocked with bandages, antiseptics, gloves, scissors, and emergency contact cards. Inspect contents monthly. Refill after any use.',
    contact: 'Safety Officer',
    photo: null,
    camDir: [1, 0.3, 0],
  },
  {
    meshName: 'Circle',
    name: 'Fire Extinguisher 6',
    category: 'Fire Safety',
    icon: '🧯',
    location: 'Zone F - Right Wing',
    description: 'CO₂ fire extinguisher rated for Class B and C fires. Suitable for electrical and flammable liquid fires. Inspect monthly and service annually.',
    contact: 'Safety Officer',
    photo: null,
    camDir: [-1, 0.4, 0.5],
  },
  {
    meshName: 'conf_table_4',
    name: 'Conference Table 4',
    category: 'Meeting Room',
    icon: '🪑',
    location: 'Open Area - Collaboration Zone',
    description: 'Open collaboration table seating up to 8 people. Located in the open office area, no booking required. Suitable for ad-hoc team meetings and workshops.',
    contact: 'Reception',
    photo: null,
  },
];
